{% include "includes/jinja/header-comment.txt" %}
FROM ubuntu:18.04

USER root

RUN apt-get update && \
    apt-get install -y \
    curl \
    git \
    unzip \
    vim \
    tree

RUN bash -c 'curl -fsSL https://raw.githubusercontent.com/odb/shml/1.1.0/shml.sh -o /usr/local/bin/shml' && \
    chmod +x /usr/local/bin/shml

{% include "includes/jinja/dev-account-setup.txt" %}

ARG github_username
ARG github_password

RUN cd ~ && \
    git clone https://github.com/wileymab/dyson .dyson && \
    echo "source ~/.dyson/environments/bashrc.sh" > ~/.bashrc